### ISSUE TITLE
Webscript Sidebar - openFileAtPath does not focus the correct tab

### ISSUE THREAD

**Issue by mt-k** [panicinc/CodaPluginKit#5]
When opening an already opend file through openFileAtPath, the selection in the tab bar does not change to the new file.

How to reproduce the issue:
* Use a simple sidebar plugin to open a file:
`<button onclick="CodaTextView.openFileAtPath('path_to/file.a')">Open</button>`
* Open file.a in coda
* Open another file.b in coda
* Click on the button in the sidebar
* file.a is shown in the editor but the tabbar shows file.b

**Comment by wadeco** [comment]
This should be resolved in the upcoming Coda 2.5.12.
